### ISSUE TITLE
HOCON config resolving

### ISSUE THREAD

**Issue by rocketraman** [jdiazcano/cfg4k#32]
The HOCON specification (https://github.com/lightbend/config/blob/master/HOCON.md#substitutions) supports referencing properties like this:

```
a: foo
b: ${a}bar
```

which should result in `b` equal to `foobar`.

However, when attempting to use resolution like this via cfg4k, I get the following stack trace:

```
Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${a})
	at com.typesafe.config.impl.ConfigReference.notResolved(ConfigReference.java:33)
	at com.typesafe.config.impl.ConfigReference.unwrapped(ConfigReference.java:45)
	at com.jdiazcano.cfg4k.hocon.HoconConfigMapperKt.parseObject(HoconConfigMapper.kt:16)
	at com.jdiazcano.cfg4k.hocon.HoconConfigMapperKt.parseObject(HoconConfigMapper.kt:15)
	at com.jdiazcano.cfg4k.hocon.HoconConfigMapperKt.toConfig(HoconConfigMapper.kt:8)
	at com.jdiazcano.cfg4k.hocon.HoconConfigLoader.<init>(HoconConfigLoader.kt:35)
	at com.jdiazcano.cfg4k.hocon.HoconConfigLoaderKt.HoconConfigLoader(HoconConfigLoader.kt:22)
	at com.jdiazcano.cfg4k.hocon.HoconConfigLoaderKt.HoconConfigLoader$default(HoconConfigLoader.kt:20)
```

**Comment by jdiazcano** [comment]
I think for now I will add support for this feature only in Hocon while I think if it should be done in a standard way inside the library. See #29 #28
