### ISSUE TITLE
RuntimeException sometimes in tests

### ISSUE THREAD

**Issue by jdiazcano** [jdiazcano/cfg4k#7]
Exception in thread "TimeReloadStrategy" java.lang.RuntimeException: No state found: INIT EOF
	at com.beust.klaxon.StateMachine.next(Parser.kt:74)
	at com.beust.klaxon.Parser.parse(Parser.kt:211)
	at com.jdiazcano.konfig.loaders.JsonConfigLoader.loadProperties(JsonConfigLoader.kt:42)
	at com.jdiazcano.konfig.loaders.JsonConfigLoader.reload(JsonConfigLoader.kt:37)
	at com.jdiazcano.konfig.providers.DefaultConfigProvider.reload(DefaultConfigProvider.kt:137)
	at com.jdiazcano.konfig.loaders.TimedReloadStrategy$register$$inlined$timer$1.run(Timer.kt:149)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

This occurs "randomly" when running test, it might be impacted by the way tests are designed (they create the file and then they destroy it)

**Comment by jdiazcano** [comment]
This seems to be related to an issue wiht my mac and intellij, it has never happened on windows or in the CI!

**Comment by jdiazcano** [comment]
Hasn't happened since the creation of the issue and I am using another computer so it is computer-related bug
